Section A practice

In [137]:
import pandas as pd

In [138]:
import numpy as np

In [139]:
data=pd.read_csv("car_fuel_efficiency.csv")

In [140]:
data.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [141]:
data.shape

(9704, 11)

In [142]:
data.dtypes

engine_displacement      int64
num_cylinders          float64
horsepower             float64
vehicle_weight         float64
acceleration           float64
model_year               int64
origin                     str
fuel_type                  str
drivetrain                 str
num_doors              float64
fuel_efficiency_mpg    float64
dtype: object

In [143]:
data.value_counts("origin")

origin
Europe    3254
Asia      3247
USA       3203
Name: count, dtype: int64

In [144]:
data.groupby("fuel_type")["fuel_efficiency_mpg"].mean()

fuel_type
Diesel      14.974123
Gasoline    14.996155
Name: fuel_efficiency_mpg, dtype: float64

In [145]:
data[(data["origin"]=="Europe") & (data["model_year"]>=2015)]["horsepower"].mean()

np.float64(148.4968888888889)

In [146]:
data.isnull().sum().max() #column with the most missing values
#column with most missing values
data.isnull().sum().idxmax()

'acceleration'

In [147]:
data.value_counts("num_doors") # the problem is that it supports negative values, so we need to filter them out and make them integer instead of float

num_doors
 0.0    3551
 1.0    2192
-1.0    2183
-2.0     594
 2.0     563
 3.0      58
-3.0      56
-4.0       4
 4.0       1
Name: count, dtype: int64

In [148]:
data["acceleration"]=data["acceleration"].fillna(data["acceleration"].mean())

In [149]:
data["acceleration"].isnull().sum()

np.int64(0)

In [150]:
x=np.array(data["vehicle_weight"])

In [151]:
x

array([3413.43375861, 3149.66493422, 3079.03899737, ..., 2583.47131761,
       2905.52738998, 2908.04347736], shape=(9704,))

In [152]:
x[:5]

array([3413.43375861, 3149.66493422, 3079.03899737, 2542.39240183,
       3460.87098999])

Section B PRACTICE

In [153]:
array=np.zeros(6)

In [154]:
print(array)

[0. 0. 0. 0. 0. 0.]

In [155]:
print(np.ones(6))

[1. 1. 1. 1. 1. 1.]

In [156]:
print(np.full(10,1)) #3ashar wa7ayed

[1 1 1 1 1 1 1 1 1 1]

In [157]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]

In [158]:
print(np.linspace(0,1,5)) #5 numbers between 0 and 1

[0.   0.25 0.5  0.75 1.  ]

In [159]:
print(np.linspace(0,10,6))

[ 0.  2.  4.  6.  8. 10.]

In [160]:
a=np.arange(10)

In [161]:
print(a)
print(a*2)
print(a**2)

print(a[a%2==0]) #even numbers

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  4  9 16 25 36 49 64 81]
[0 2 4 6 8]

In [162]:
np.random.seed(42)
np.random.rand(3,2)
#idk why with the random seed

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452]])

In [163]:
u = np.array([1,2,3])
print (u)
v = np.array([4,5,6])

[1 2 3]

In [164]:
def dot(u,v):
    result=0
    for i in range(len(u)):
        result+=u[i]*v[i]
    return np.array(result)

In [165]:
U = np.array([[1,2,3],[4,5,6]])
print (U)

[[1 2 3]
 [4 5 6]]

In [166]:
def matvec(U,v):
    result=[]
    for row in U:
        value=dot(row,v)
        result.append(value)
    return np.array(result)

In [167]:
matvec(U,v)

array([32, 77])

In [168]:
print (V[:-1])

NameError: name 'V' is not defined

In [ ]:
V=np.array([[1, 0], [0, 1], [2, 3]])
U = np.array([[1, 2, 3], [4, 5, 6]])
def matmat(U, V):
    result = []
    for i in range(V.shape[1]):     # V.shape is (3, 2); [1] picks the 2 = number of columns
        column = V[:, i]            # ":" = all rows, "i" = column i → [1, 0, 2], then [0, 1, 3]
        result.append(matvec(U, column))   # U times this column → one column of the answer
    return np.array(result).T       # results were stacked as rows; .T flips them into columns
matmat(U,V)

array([[ 7, 11],
       [16, 23]])

In [ ]:
print (np.eye(4))

np.allclose(matmat(U,np.eye(3)),U)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

True

In [ ]:
A=np.array([[2,1],[1,3]])

In [ ]:
np.allclose(matmat(A,np.linalg.inv(A)),np.eye(2))

True

In [ ]:
S=np.array([[1,2],[2,4]])
np.linalg.inv(S)

LinAlgError: Singular matrix

In [ ]:
# so since row 2 is only multipllication of row 1, so row 2 adds no new information and its only a duplicate so its a singular matrix that has no inverse ( only one row )

Section C ->

In [ ]:
data.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [ ]:
europe=data[data["origin"]=="Europe"]
europe.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369
5,190,3.0,NaN,2484.883986,14.7,2008,Europe,Gasoline,All-wheel drive,-1.0,17.271818
10,230,5.0,100.0,3111.810181,15.4,2014,Europe,Diesel,All-wheel drive,0.0,13.386605

In [ ]:
europe=europe[["engine_displacement", "horsepower", "fuel_efficiency_mpg"]]

In [ ]:
europe.isnull().sum()

engine_displacement      0
horsepower             238
fuel_efficiency_mpg      0
dtype: int64

In [ ]:
europe.dropna()

      engine_displacement  horsepower  fuel_efficiency_mpg
0                     170       159.0            13.231729
2                     170        78.0            14.246341
4                     210       140.0            12.488369
10                    230       100.0            13.386605
13                    170       193.0            18.792742
...                   ...         ...                  ...
9694                  220       176.0            16.233553
9695                  280       154.0            10.542970
9696                  190        69.0            13.418128
9697                  220       110.0            17.305653
9699                  140       164.0            15.101802

[3016 rows x 3 columns]

In [169]:
europe.isnull().sum()

engine_displacement    0
horsepower             0
fuel_efficiency_mpg    0
dtype: int64

In [ ]:
len(europe)

3254

In [ ]:
europe=europe.dropna()
len(europe)

3016

In [170]:
europe.head(10)

    engine_displacement  horsepower  fuel_efficiency_mpg
0                   170       159.0            13.231729
2                   170        78.0            14.246341
4                   210       140.0            12.488369
10                  230       100.0            13.386605
13                  170       193.0            18.792742
16                  160       180.0            17.516176
18                  250       110.0            14.735962
19                  180       126.0            15.097137
22                  190       144.0            17.080405
23                  230       160.0            13.738381

In [195]:
sub=europe.head(10)
X=sub[["engine_displacement","horsepower"]].values
Y=sub["fuel_efficiency_mpg"].values

In [194]:
print(X.shape)            # 10,2
print(X.T.shape)          # 2,10
print((X.T @ X).shape)    # 2,10 @ 10,2 (inner same, outer stays and inner discarded)
print((X @ X.T).shape)    # ? 10,2 @ 2,10 ← the other order. What happens?

(10, 2)
(2, 10)
(2, 2)
(10, 10)

In [204]:
w=(np.linalg.inv(X.T@X)@X.T@Y)
print(w)
print (Y.shape)

[0.03174889 0.06213899]
(10,)

In [ ]:
y_pred=X@w  #10,2 * 2,1
print(y_pred)

[15.27741086 10.244153   15.36672592 13.51614438 17.39013638 16.26484061
 14.77251213 13.54431327 14.98030396 17.24448353]

In [215]:
print(y_pred.round(2))
print(Y.round(2))


print(np.mean(np.abs(y_pred-Y)))

[15.28 10.24 15.37 13.52 17.39 16.26 14.77 13.54 14.98 17.24]
[13.23 14.25 12.49 13.39 18.79 17.52 14.74 15.1  17.08 13.74]
1.890528483785138

In [217]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_pred,Y)

1.890528483785138